//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfConverter.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System")]
        public string ThemeMode
        {
            get
            {
                return ((string)(this["ThemeMode"]));
            }
            set
            {
                this["ThemeMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MicrosoftWord")]
        public string WordToPdfBackend
        {
            get
            {
                return ((string)(this["WordToPdfBackend"]));
            }
            set
            {
                this["WordToPdfBackend"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LibreOfficePath
        {
            get
            {
                return ((string)(this["LibreOfficePath"]));
            }
            set
            {
                this["LibreOfficePath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Standard")]
        public string WordToPdfPdfFormat
        {
            get
            {
                return ((string)(this["WordToPdfPdfFormat"]));
            }
            set
            {
                this["WordToPdfPdfFormat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Print")]
        public string WordToPdfOptimizeFor
        {
            get
            {
                return ((string)(this["WordToPdfOptimizeFor"]));
            }
            set
            {
                this["WordToPdfOptimizeFor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WordToPdfExportBookmarks
        {
            get
            {
                return ((bool)(this["WordToPdfExportBookmarks"]));
            }
            set
            {
                this["WordToPdfExportBookmarks"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WordToPdfExportComments
        {
            get
            {
                return ((bool)(this["WordToPdfExportComments"]));
            }
            set
            {
                this["WordToPdfExportComments"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Png")]
        public string OutputImageFormat
        {
            get
            {
                return ((string)(this["OutputImageFormat"]));
            }
            set
            {
                this["OutputImageFormat"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Width")]
        public string ResolutionMode
        {
            get
            {
                return ((string)(this["ResolutionMode"]));
            }
            set
            {
                this["ResolutionMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1080")]
        public string ResolutionValue
        {
            get
            {
                return ((string)(this["ResolutionValue"]));
            }
            set
            {
                this["ResolutionValue"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreserveTransparency
        {
            get
            {
                return ((bool)(this["PreserveTransparency"]));
            }
            set
            {
                this["PreserveTransparency"] = value;
            }
        }
    }
}
